name: Windows 2022

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  NRPyUnitTests:

    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11.0"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Brew install needed TeX packages (for pdflatex)
    #   run: |
    #     choco install texlive
    #     choco install ffmpeg pandoc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install --upgrade nbconvert
        python -m pip install testfixtures sympy mpmath jupyter matplotlib scipy clang_format
        python -m pip install git+https://github.com/zachetienne/nrpylatex.git
    - name: NRPyUnitTests
      run: |
        bash ./UnitTesting/run_NRPy_UnitTests.sh python3
